apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: hoshid
  labels:
    app: frontend
spec:
  type: LoadBalancer
  # クラウド環境では NodePort も可能
  # type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 443
      targetPort: 3000
      protocol: TCP
      name: https
  selector:
    app: frontend
