apiVersion: v1
kind: ConfigMap
metadata:
  name: hoshid-config
  namespace: hoshid
data:
  PORT: "3000"
  NODE_ENV: "production"
  NEXT_PUBLIC_APP_URL: "https://hoshid.example.com"
  DATABASE_URL: "postgres://hoshid_user:changeme@db-service.hoshid.svc.cluster.local:5432/hoshid?sslmode=require"
