apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hoshid

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - db/persistentvolume.yaml
  - db/persistentvolumeclaim.yaml
  - db/service.yaml
  - db/statefulset.yaml
  - frontend/serviceaccount.yaml
  - frontend/service.yaml
  - frontend/deployment.yaml
  - frontend/ingress.yaml
  - frontend/migration-job.yaml

images:
  - name: hoshid/frontend
    newTag: latest

commonLabels:
  app.kubernetes.io/name: hoshid
  app.kubernetes.io/part-of: hoshid
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  deployment.date: "2026-06-02"
